use std::{env, fs, io::Write, path::PathBuf};

fn main() {
    emit_git_hash();
    generate_embedded_svg_table();
}

fn emit_git_hash() {
    // Only emit GIT_HASH when we have one. When the build runs outside a git
    // context (e.g. a user building from the GitHub-auto-generated source
    // tarball), option_env!("GIT_HASH") returns None and the about modal
    // hides the "Commit" row instead of showing a placeholder. Mirrors rmpc's
    // pattern with vergen-gitcl.
    let hash = std::process::Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_default();

    if !hash.is_empty() {
        println!("cargo:rustc-env=GIT_HASH={hash}");
    }
}

/// Walk `assets/icons/`, emit `OUT_DIR/embedded_svg_generated.rs` containing a
/// match-based lookup function + `KNOWN_PATHS` array. Adding/removing an icon
/// is now a one-step change (drop or remove the file in `assets/icons/` and
/// rebuild) — no manual const + match arm + KNOWN-list edits required.
fn generate_embedded_svg_table() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo"));

    // Two icon namespaces are embedded into one lookup table keyed by the full
    // relative path: the canonical Lucide set under `assets/icons/` (the
    // literal paths every view references) and the alternate Phosphor set
    // under `assets/icons-phosphor/`, which `embedded_svg::get_svg` resolves
    // at runtime when the user selects the Phosphor icon set.
    let icon_dirs = ["assets/icons", "assets/icons-phosphor"];

    // Full relative paths, e.g. "assets/icons/play.svg" /
    // "assets/icons-phosphor/play-fill.svg".
    let mut svgs: Vec<String> = Vec::new();
    for rel in icon_dirs {
        let dir = manifest_dir.join(rel);
        println!("cargo:rerun-if-changed={}", dir.display());
        let entries = fs::read_dir(&dir).unwrap_or_else(|e| panic!("read {}: {e}", dir.display()));
        svgs.extend(entries.filter_map(|entry| {
            let path = entry.ok()?.path();
            if path.extension().is_some_and(|e| e == "svg") {
                Some(format!("{rel}/{}", path.file_name()?.to_str()?))
            } else {
                None
            }
        }));
    }
    svgs.sort();

    assert!(
        svgs.iter().any(|f| f == "assets/icons/play.svg"),
        "assets/icons/play.svg is the embedded_svg fallback and must exist"
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let out_path = out_dir.join("embedded_svg_generated.rs");
    let mut out = fs::File::create(&out_path)
        .unwrap_or_else(|e| panic!("create {}: {e}", out_path.display()));

    let expect_msg = "write to embedded_svg manifest";

    writeln!(
        out,
        "// Auto-generated by build.rs from assets/icons/ + assets/icons-phosphor/. Do not edit by hand.\n"
    )
    .expect(expect_msg);

    // Lookup function: returns Some(content) for known paths, None for unknown.
    // The wrapping module in src/embedded_svg.rs handles the play.svg fallback +
    // tracing warning, so the generated code stays free of crate dependencies.
    writeln!(
        out,
        "pub(super) fn lookup(path: &str) -> Option<&'static str> {{"
    )
    .expect(expect_msg);
    writeln!(out, "    match path {{").expect(expect_msg);
    for file in &svgs {
        writeln!(
            out,
            "        \"{file}\" => Some(include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{file}\"))),"
        )
        .expect(expect_msg);
    }
    writeln!(out, "        _ => None,").expect(expect_msg);
    writeln!(out, "    }}").expect(expect_msg);
    writeln!(out, "}}\n").expect(expect_msg);

    writeln!(
        out,
        "pub(super) const FALLBACK: &str = include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/assets/icons/play.svg\"));\n"
    )
    .expect(expect_msg);

    writeln!(out, "#[cfg(test)]").expect(expect_msg);
    writeln!(out, "pub(super) const KNOWN_PATHS: &[&str] = &[").expect(expect_msg);
    for file in &svgs {
        writeln!(out, "    \"{file}\",").expect(expect_msg);
    }
    writeln!(out, "];").expect(expect_msg);
}
