use std::{env, fs, io::Write, path::PathBuf};

fn main() {
    emit_git_hash();
    generate_embedded_svg_table();
}

fn emit_git_hash() {
    // Only emit GIT_HASH when we have one. When the build runs outside a git
    // context (e.g. a user building from the GitHub-auto-generated source
    // tarball), option_env!("GIT_HASH") returns None and the about modal
    // hides the "Commit" row instead of showing a placeholder. Mirrors rmpc's
    // pattern with vergen-gitcl.
    let hash = std::process::Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_default();

    if !hash.is_empty() {
        println!("cargo:rustc-env=GIT_HASH={hash}");
    }
}

/// Walk `assets/icons/`, emit `OUT_DIR/embedded_svg_generated.rs` containing a
/// match-based lookup function + `KNOWN_PATHS` array. Adding/removing an icon
/// is now a one-step change (drop or remove the file in `assets/icons/` and
/// rebuild) — no manual const + match arm + KNOWN-list edits required.
fn generate_embedded_svg_table() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo"));
    let icons_dir = manifest_dir.join("assets").join("icons");

    println!("cargo:rerun-if-changed={}", icons_dir.display());

    let mut svgs: Vec<String> = fs::read_dir(&icons_dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", icons_dir.display()))
        .filter_map(|entry| {
            let path = entry.ok()?.path();
            if path.extension().is_some_and(|e| e == "svg") {
                path.file_name()?.to_str().map(str::to_owned)
            } else {
                None
            }
        })
        .collect();
    svgs.sort();

    assert!(
        svgs.iter().any(|f| f == "play.svg"),
        "assets/icons/play.svg is the embedded_svg fallback and must exist"
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let out_path = out_dir.join("embedded_svg_generated.rs");
    let mut out = fs::File::create(&out_path)
        .unwrap_or_else(|e| panic!("create {}: {e}", out_path.display()));

    writeln!(
        out,
        "// Auto-generated by build.rs from assets/icons/. Do not edit by hand.\n"
    )
    .unwrap();

    // Lookup function: returns Some(content) for known paths, None for unknown.
    // The wrapping module in src/embedded_svg.rs handles the play.svg fallback +
    // tracing warning, so the generated code stays free of crate dependencies.
    writeln!(
        out,
        "pub(super) fn lookup(path: &str) -> Option<&'static str> {{"
    )
    .unwrap();
    writeln!(out, "    match path {{").unwrap();
    for file in &svgs {
        writeln!(
            out,
            "        \"assets/icons/{file}\" => Some(include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/assets/icons/{file}\"))),"
        )
        .unwrap();
    }
    writeln!(out, "        _ => None,").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}\n").unwrap();

    writeln!(
        out,
        "pub(super) const FALLBACK: &str = include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/assets/icons/play.svg\"));\n"
    )
    .unwrap();

    writeln!(out, "#[cfg(test)]").unwrap();
    writeln!(out, "pub(super) const KNOWN_PATHS: &[&str] = &[").unwrap();
    for file in &svgs {
        writeln!(out, "    \"assets/icons/{file}\",").unwrap();
    }
    writeln!(out, "];").unwrap();
}
