//! Settings service — view preferences, player settings, hotkey bindings
//!
//! Wraps `SettingsManager` for persisting sort preferences, volume,
//! visualization mode, and user-configurable hotkey bindings via redb.
//! Light mode is stored in config.toml (see `config_writer`).
//!
//! Most methods are pure pass-through wrappers around `SettingsManager`,
//! generated by the file-private `delegate_setter!` and `delegate_getter!`
//! macros below. Methods kept inline are the ones that can't be pure
//! pass-throughs: multi-arg signatures, type casts (f32→f64 for volume),
//! two-call-under-one-lock sequences (hotkeys), and the constructor /
//! lock escape hatch.

use std::sync::Arc;

use tokio::sync::Mutex;

use crate::{
    services::settings::SettingsManager,
    types::{
        hotkey_config::{HotkeyAction, HotkeyConfig, KeyCombo},
        player_settings::{
            ArtworkColumnMode, ArtworkResolution, ArtworkStretchFit, EnterBehavior,
            LibraryPageSize, NavDisplayMode, NavLayout, NormalizationLevel, PlayerSettings,
            SlotRowHeight, StripClickAction, StripSeparator, TrackInfoDisplay, VisualizationMode,
            VolumeNormalizationMode,
        },
        queue_sort_mode::QueueSortMode,
        sort_mode::SortMode,
        view_preferences::AllViewPreferences,
    },
};

/// Async setter that locks the manager mutex and forwards a single argument
/// to the identically-named method on `SettingsManager`. Use only for pure
/// pass-through delegations — anything with a cast, multi-arg signature, or
/// post-action under the same lock must be written inline.
///
/// Optional leading attributes (e.g. `///` doc comments) are forwarded to the
/// generated method.
macro_rules! delegate_setter {
    ($(#[$attr:meta])* $name:ident, $arg:ty) => {
        $(#[$attr])*
        pub async fn $name(&self, v: $arg) -> anyhow::Result<()> {
            let mut sm = self.settings_manager.lock().await;
            sm.$name(v)
        }
    };
}

/// Async zero-arg getter that locks the manager mutex and forwards to the
/// identically-named method on `SettingsManager`. Use only for pure
/// pass-through delegations.
macro_rules! delegate_getter {
    ($(#[$attr:meta])* $name:ident, $ret:ty) => {
        $(#[$attr])*
        pub async fn $name(&self) -> $ret {
            let sm = self.settings_manager.lock().await;
            sm.$name()
        }
    };
}

/// Service wrapper for SettingsManager
///
/// Provides Arc<Mutex<>> access pattern consistent with other ViewModels.
#[derive(Clone)]
pub struct SettingsService {
    settings_manager: Arc<Mutex<SettingsManager>>,
}

impl std::fmt::Debug for SettingsService {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SettingsService").finish()
    }
}

impl SettingsService {
    pub fn new(storage: crate::services::state_storage::StateStorage) -> anyhow::Result<Self> {
        let settings_manager = SettingsManager::new(storage)?;
        Ok(Self {
            settings_manager: Arc::new(Mutex::new(settings_manager)),
        })
    }

    /// Get reference to SettingsManager
    pub fn settings_manager(&self) -> Arc<Mutex<SettingsManager>> {
        self.settings_manager.clone()
    }

    /// Reload settings from config.toml
    pub async fn reload_from_toml(&self) {
        let mut sm = self.settings_manager.lock().await;
        sm.reload_from_toml();
    }

    // =========================================================================
    // View Sort Preferences (multi-arg — kept inline)
    // =========================================================================

    pub async fn set_albums_prefs(
        &self,
        sort_mode: SortMode,
        sort_ascending: bool,
    ) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_albums_prefs(sort_mode, sort_ascending)
    }

    pub async fn set_artists_prefs(
        &self,
        sort_mode: SortMode,
        sort_ascending: bool,
    ) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_artists_prefs(sort_mode, sort_ascending)
    }

    pub async fn set_songs_prefs(
        &self,
        sort_mode: SortMode,
        sort_ascending: bool,
    ) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_songs_prefs(sort_mode, sort_ascending)
    }

    pub async fn set_genres_prefs(
        &self,
        sort_mode: SortMode,
        sort_ascending: bool,
    ) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_genres_prefs(sort_mode, sort_ascending)
    }

    pub async fn set_playlists_prefs(
        &self,
        sort_mode: SortMode,
        sort_ascending: bool,
    ) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_playlists_prefs(sort_mode, sort_ascending)
    }

    pub async fn set_queue_prefs(
        &self,
        sort_mode: QueueSortMode,
        sort_ascending: bool,
    ) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_queue_prefs(sort_mode, sort_ascending)
    }

    delegate_getter!(get_view_preferences, AllViewPreferences);

    // =========================================================================
    // Player Settings — bulk getter and volume (f32→f64 cast, kept inline)
    // =========================================================================

    delegate_getter!(get_player_settings, PlayerSettings);

    /// Persist volume setting
    pub async fn set_volume(&self, volume: f32) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_volume(volume as f64)
    }

    /// Set SFX volume (0.0 to 1.0) and persist
    pub async fn set_sfx_volume(&self, volume: f32) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_sfx_volume(volume as f64)
    }

    // =========================================================================
    // Single-arg setters (macro-generated)
    // =========================================================================

    delegate_setter!(set_sound_effects_enabled, bool);
    delegate_setter!(set_visualization_mode, VisualizationMode);
    delegate_setter!(set_scrobbling_enabled, bool);
    delegate_setter!(set_scrobble_threshold, f64);
    delegate_setter!(set_start_view, &str);
    delegate_setter!(set_stable_viewport, bool);
    delegate_setter!(set_show_album_artists_only, bool);
    delegate_setter!(set_suppress_library_refresh_toasts, bool);
    delegate_setter!(set_show_tray_icon, bool);
    delegate_setter!(set_close_to_tray, bool);
    delegate_setter!(set_rounded_mode, bool);
    delegate_setter!(set_nav_layout, NavLayout);
    delegate_setter!(set_nav_display_mode, NavDisplayMode);
    delegate_setter!(set_track_info_display, TrackInfoDisplay);
    delegate_setter!(set_auto_follow_playing, bool);
    delegate_setter!(set_enter_behavior, EnterBehavior);
    delegate_setter!(set_local_music_path, String);
    delegate_setter!(set_library_page_size, LibraryPageSize);
    delegate_setter!(set_artwork_resolution, ArtworkResolution);
    delegate_setter!(set_eq_enabled, bool);
    delegate_setter!(set_eq_gains, [f32; 10]);
    delegate_setter!(delete_custom_eq_preset, usize);
    delegate_setter!(set_slot_row_height, SlotRowHeight);
    delegate_setter!(set_opacity_gradient, bool);
    delegate_setter!(set_slot_text_links, bool);
    delegate_setter!(set_crossfade_enabled, bool);
    delegate_setter!(set_crossfade_duration, u32);
    delegate_setter!(set_quick_add_to_playlist, bool);
    delegate_setter!(set_queue_show_default_playlist, bool);
    delegate_setter!(set_horizontal_volume, bool);
    delegate_setter!(set_font_family, String);

    // -- Track info strip toggles --
    delegate_setter!(set_strip_show_title, bool);
    delegate_setter!(set_strip_show_artist, bool);
    delegate_setter!(set_strip_show_album, bool);
    delegate_setter!(set_strip_show_format_info, bool);
    delegate_setter!(set_strip_merged_mode, bool);
    delegate_setter!(set_strip_click_action, StripClickAction);
    delegate_setter!(
        /// Set strip label visibility (`title:` / `artist:` / `album:` prefixes)
        set_strip_show_labels, bool
    );
    delegate_setter!(set_strip_separator, StripSeparator);

    // -- Per-view artwork text overlay --
    delegate_setter!(set_albums_artwork_overlay, bool);
    delegate_setter!(set_artists_artwork_overlay, bool);
    delegate_setter!(set_songs_artwork_overlay, bool);
    delegate_setter!(set_playlists_artwork_overlay, bool);

    // -- Artwork column (slot list) --
    delegate_setter!(set_artwork_column_mode, ArtworkColumnMode);
    delegate_setter!(set_artwork_column_stretch_fit, ArtworkStretchFit);
    delegate_setter!(
        /// Set the artwork column width fraction (0.05..=0.80)
        set_artwork_column_width_pct, f32
    );

    // -- Per-view column visibility --
    delegate_setter!(set_queue_show_stars, bool);
    delegate_setter!(set_queue_show_album, bool);
    delegate_setter!(set_queue_show_duration, bool);
    delegate_setter!(set_queue_show_love, bool);
    delegate_setter!(set_queue_show_plays, bool);
    delegate_setter!(set_queue_show_index, bool);
    delegate_setter!(set_queue_show_thumbnail, bool);
    delegate_setter!(set_queue_show_genre, bool);
    delegate_setter!(set_queue_show_select, bool);
    delegate_setter!(set_albums_show_stars, bool);
    delegate_setter!(set_albums_show_songcount, bool);
    delegate_setter!(set_albums_show_plays, bool);
    delegate_setter!(set_albums_show_love, bool);
    delegate_setter!(set_albums_show_index, bool);
    delegate_setter!(set_albums_show_thumbnail, bool);
    delegate_setter!(set_albums_show_select, bool);
    delegate_setter!(set_songs_show_stars, bool);
    delegate_setter!(set_songs_show_album, bool);
    delegate_setter!(set_songs_show_duration, bool);
    delegate_setter!(set_songs_show_plays, bool);
    delegate_setter!(set_songs_show_love, bool);
    delegate_setter!(set_songs_show_index, bool);
    delegate_setter!(set_songs_show_thumbnail, bool);
    delegate_setter!(set_songs_show_genre, bool);
    delegate_setter!(set_songs_show_select, bool);
    delegate_setter!(set_artists_show_stars, bool);
    delegate_setter!(set_artists_show_albumcount, bool);
    delegate_setter!(set_artists_show_songcount, bool);
    delegate_setter!(set_artists_show_plays, bool);
    delegate_setter!(set_artists_show_love, bool);
    delegate_setter!(set_artists_show_index, bool);
    delegate_setter!(set_artists_show_thumbnail, bool);
    delegate_setter!(set_artists_show_select, bool);
    delegate_setter!(set_genres_show_index, bool);
    delegate_setter!(set_genres_show_thumbnail, bool);
    delegate_setter!(set_genres_show_albumcount, bool);
    delegate_setter!(set_genres_show_songcount, bool);
    delegate_setter!(set_genres_show_select, bool);
    delegate_setter!(set_playlists_show_index, bool);
    delegate_setter!(set_playlists_show_thumbnail, bool);
    delegate_setter!(set_playlists_show_songcount, bool);
    delegate_setter!(set_playlists_show_duration, bool);
    delegate_setter!(set_playlists_show_updatedat, bool);
    delegate_setter!(set_playlists_show_select, bool);
    delegate_setter!(set_similar_show_index, bool);
    delegate_setter!(set_similar_show_thumbnail, bool);
    delegate_setter!(set_similar_show_album, bool);
    delegate_setter!(set_similar_show_duration, bool);
    delegate_setter!(set_similar_show_love, bool);
    delegate_setter!(set_similar_show_select, bool);

    // -- Volume normalization / ReplayGain --
    delegate_setter!(set_volume_normalization, VolumeNormalizationMode);
    delegate_setter!(
        /// Set normalization level (AGC mode only)
        set_normalization_level, NormalizationLevel
    );
    delegate_setter!(set_replay_gain_preamp_db, f32);
    delegate_setter!(
        /// Set ReplayGain fallback dB (used when track has no tags)
        set_replay_gain_fallback_db, f32
    );
    delegate_setter!(set_replay_gain_fallback_to_agc, bool);
    delegate_setter!(
        /// Set ReplayGain peak-aware clipping prevention
        set_replay_gain_prevent_clipping, bool
    );

    delegate_setter!(set_verbose_config, bool);

    // =========================================================================
    // Multi-arg setters (kept inline)
    // =========================================================================

    pub async fn save_custom_eq_preset(
        &self,
        name: String,
        gains: [f32; 10],
    ) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.save_custom_eq_preset(name, gains)
    }

    /// Set default playlist for quick-add and persist
    pub async fn set_default_playlist(
        &self,
        id: Option<String>,
        name: String,
    ) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_default_playlist(id, name)
    }

    /// Set active playlist context (for queue header bar) and persist
    pub async fn set_active_playlist(
        &self,
        id: Option<String>,
        name: String,
        comment: String,
    ) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_active_playlist(id, name, comment)
    }

    // =========================================================================
    // Hotkey bindings (two-call-under-one-lock — kept inline)
    // =========================================================================

    /// Set a single hotkey binding, persist, and return updated config
    pub async fn set_hotkey_binding(
        &self,
        action: HotkeyAction,
        combo: KeyCombo,
    ) -> anyhow::Result<HotkeyConfig> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_hotkey_binding(action, combo)?;
        Ok(sm.get_hotkey_config_owned())
    }

    /// Reset a single hotkey to default, persist, and return updated config
    pub async fn reset_hotkey(&self, action: &HotkeyAction) -> anyhow::Result<HotkeyConfig> {
        let mut sm = self.settings_manager.lock().await;
        sm.reset_hotkey(action)?;
        Ok(sm.get_hotkey_config_owned())
    }

    /// Reset all hotkeys to defaults, persist, and return updated config
    pub async fn reset_all_hotkeys(&self) -> anyhow::Result<HotkeyConfig> {
        let mut sm = self.settings_manager.lock().await;
        sm.reset_all_hotkeys()?;
        Ok(sm.get_hotkey_config_owned())
    }

    /// Get the current hotkey configuration. Service method name differs from
    /// the underlying `SettingsManager::get_hotkey_config_owned()` — kept inline.
    pub async fn get_hotkey_config(&self) -> HotkeyConfig {
        let sm = self.settings_manager.lock().await;
        sm.get_hotkey_config_owned()
    }
}
