//! Settings service — view preferences, player settings, hotkey bindings
//!
//! Wraps `SettingsManager` for persisting sort preferences, volume,
//! visualization mode, and user-configurable hotkey bindings via redb.
//! Light mode is stored in config.toml (see `config_writer`).
//!
//! Holds only the methods the UI calls on the service. Settings-tab writes
//! lock `SettingsManager` directly through `settings_manager()` and the
//! `dispatch_*_tab_setting` functions in `settings_tables`, so a new setting
//! needs no wrapper here. Pure single-argument pass-throughs are generated by
//! the file-private `delegate_setter!` and `delegate_getter!` macros below;
//! the rest are written inline: multi-arg signatures, type casts (f32→f64 for
//! volume), two-call-under-one-lock sequences (hotkeys), and the constructor
//! / lock escape hatch.

use std::sync::Arc;

use tokio::sync::Mutex;

use crate::{
    services::settings::{ColumnPersist, SettingsManager},
    types::{
        hotkey_config::{HotkeyAction, HotkeyConfig, KeyCombo},
        player_settings::{BitPerfectMode, LivePlayerSettings, VisualizationMode},
        queue_sort_mode::QueueSortMode,
        sort_mode::SortMode,
        view_preferences::AllViewPreferences,
    },
};

/// Async setter that locks the manager mutex and forwards a single argument
/// to the identically-named method on `SettingsManager`. Use only for pure
/// pass-through delegations — anything with a cast, multi-arg signature, or
/// post-action under the same lock must be written inline.
///
/// Optional leading attributes (e.g. `///` doc comments) are forwarded to the
/// generated method.
macro_rules! delegate_setter {
    ($(#[$attr:meta])* $name:ident, $arg:ty) => {
        $(#[$attr])*
        pub async fn $name(&self, v: $arg) -> anyhow::Result<()> {
            let mut sm = self.settings_manager.lock().await;
            sm.$name(v)
        }
    };
}

/// Async zero-arg getter that locks the manager mutex and forwards to the
/// identically-named method on `SettingsManager`. Use only for pure
/// pass-through delegations.
macro_rules! delegate_getter {
    ($(#[$attr:meta])* $name:ident, $ret:ty) => {
        $(#[$attr])*
        pub async fn $name(&self) -> $ret {
            let sm = self.settings_manager.lock().await;
            sm.$name()
        }
    };
}

/// Service wrapper for SettingsManager
///
/// Provides Arc<Mutex<>> access pattern consistent with other ViewModels.
#[derive(Clone)]
pub struct SettingsService {
    settings_manager: Arc<Mutex<SettingsManager>>,
}

impl std::fmt::Debug for SettingsService {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SettingsService").finish()
    }
}

impl SettingsService {
    pub fn new(storage: crate::services::state_storage::StateStorage) -> anyhow::Result<Self> {
        let settings_manager = SettingsManager::new(storage)?;
        Ok(Self {
            settings_manager: Arc::new(Mutex::new(settings_manager)),
        })
    }

    /// Get reference to SettingsManager
    pub fn settings_manager(&self) -> Arc<Mutex<SettingsManager>> {
        self.settings_manager.clone()
    }

    /// Reload settings from config.toml. See
    /// [`SettingsManager::reload_from_toml`] for the `Ok` / `Err` contract.
    pub async fn reload_from_toml(
        &self,
    ) -> anyhow::Result<Vec<crate::services::toml_settings_io::TomlSection>> {
        let mut sm = self.settings_manager.lock().await;
        sm.reload_from_toml()
    }

    // =========================================================================
    // View Sort Preferences (multi-arg — kept inline)
    // =========================================================================

    pub async fn set_albums_prefs(
        &self,
        sort_mode: SortMode,
        sort_ascending: bool,
    ) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_albums_prefs(sort_mode, sort_ascending)
    }

    pub async fn set_artists_prefs(
        &self,
        sort_mode: SortMode,
        sort_ascending: bool,
    ) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_artists_prefs(sort_mode, sort_ascending)
    }

    pub async fn set_songs_prefs(
        &self,
        sort_mode: SortMode,
        sort_ascending: bool,
    ) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_songs_prefs(sort_mode, sort_ascending)
    }

    pub async fn set_genres_prefs(
        &self,
        sort_mode: SortMode,
        sort_ascending: bool,
    ) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_genres_prefs(sort_mode, sort_ascending)
    }

    pub async fn set_playlists_prefs(
        &self,
        sort_mode: SortMode,
        sort_ascending: bool,
    ) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_playlists_prefs(sort_mode, sort_ascending)
    }

    pub async fn set_queue_prefs(
        &self,
        sort_mode: QueueSortMode,
        sort_ascending: bool,
    ) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_queue_prefs(sort_mode, sort_ascending)
    }

    delegate_getter!(get_view_preferences, AllViewPreferences);

    // =========================================================================
    // Player Settings — bulk getter and volume (f32→f64 cast, kept inline)
    // =========================================================================

    delegate_getter!(get_player_settings, LivePlayerSettings);

    /// Persist volume setting
    pub async fn set_volume(&self, volume: f32) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_volume(volume as f64)
    }

    /// Set SFX volume (0.0 to 1.0) and persist
    pub async fn set_sfx_volume(&self, volume: f32) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_sfx_volume(volume as f64)
    }

    // =========================================================================
    // Single-arg setters (macro-generated)
    //
    // Only the setters the UI calls directly. Settings-tab writes go through
    // `dispatch_*_tab_setting` against `SettingsManager`, not through here.
    // =========================================================================

    delegate_setter!(set_sound_effects_enabled, bool);
    delegate_setter!(set_visualization_mode, VisualizationMode);
    delegate_setter!(set_local_music_path, String);
    delegate_setter!(set_eq_enabled, bool);
    delegate_setter!(set_eq_gains, [f32; 10]);
    delegate_setter!(delete_custom_eq_preset, usize);
    delegate_setter!(set_crossfade_enabled, bool);
    delegate_setter!(set_bit_perfect, BitPerfectMode);
    delegate_setter!(set_font_family, String);
    delegate_setter!(
        /// Set the artwork column width fraction (0.05..=0.80)
        set_artwork_column_width_pct,
        f32
    );
    delegate_setter!(
        /// Set the Always-Vertical artwork height fraction (0.10..=0.80)
        set_artwork_vertical_height_pct,
        f32
    );

    /// Persist a single column visibility toggle using the `ColumnPersist` impl
    /// emitted by `define_view_columns!`. Replaces the 7 per-view
    /// `persist_*_column_visibility` helpers on `Nokkvi`.
    pub async fn set_column_visibility<C: ColumnPersist>(
        &self,
        col: C,
        value: bool,
    ) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        col.apply_to_settings(&mut sm, value)
    }

    // =========================================================================
    // Multi-arg setters (kept inline)
    // =========================================================================

    pub async fn save_custom_eq_preset(
        &self,
        name: String,
        gains: [f32; 10],
    ) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.save_custom_eq_preset(name, gains)
    }

    /// Set default playlist for quick-add and persist
    pub async fn set_default_playlist(
        &self,
        id: Option<String>,
        name: String,
    ) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_default_playlist(id, name)
    }

    /// Set active playlist context (for queue header bar) and persist;
    /// `None` clears it.
    pub async fn set_active_playlist(
        &self,
        record: Option<crate::types::active_playlist::ActivePlaylistRecord>,
    ) -> anyhow::Result<()> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_active_playlist(record)
    }

    // =========================================================================
    // Hotkey bindings (two-call-under-one-lock — kept inline)
    // =========================================================================

    /// Set a single hotkey binding, persist, and return updated config
    pub async fn set_hotkey_binding(
        &self,
        action: HotkeyAction,
        combo: KeyCombo,
    ) -> anyhow::Result<HotkeyConfig> {
        let mut sm = self.settings_manager.lock().await;
        sm.set_hotkey_binding(action, combo)?;
        Ok(sm.get_hotkey_config_owned())
    }

    /// Reset a single hotkey to default, persist, and return updated config
    pub async fn reset_hotkey(&self, action: &HotkeyAction) -> anyhow::Result<HotkeyConfig> {
        let mut sm = self.settings_manager.lock().await;
        sm.reset_hotkey(action)?;
        Ok(sm.get_hotkey_config_owned())
    }

    /// Reset all hotkeys to defaults, persist, and return updated config
    pub async fn reset_all_hotkeys(&self) -> anyhow::Result<HotkeyConfig> {
        let mut sm = self.settings_manager.lock().await;
        sm.reset_all_hotkeys()?;
        Ok(sm.get_hotkey_config_owned())
    }

    /// Get the current hotkey configuration. Service method name differs from
    /// the underlying `SettingsManager::get_hotkey_config_owned()` — kept inline.
    pub async fn get_hotkey_config(&self) -> HotkeyConfig {
        let sm = self.settings_manager.lock().await;
        sm.get_hotkey_config_owned()
    }
}
