# Navidrome Client Configuration - Gruvbox Dark Hard Red
# The classic Gruvbox theme with red accent

# REPLACE THESE WITH YOUR CREDENTIALS
server_url = "http://localhost:4533"
username = ""

[theme.dark.accent]
border_dark = "#cc241d"
border_light = "#fb4934"
bright = "#fb4934"
primary = "#cc241d"

[theme.dark.aqua]
bright = "#8ec07c"
normal = "#689d6a"

[theme.dark.background]
default = "#282828"
hard = "#1d2021"
level1 = "#3c3836"
level2 = "#504945"
level3 = "#665c54"
level4 = "#7c6f64"
soft = "#32302f"

[theme.dark.foreground]
bright = "#fbf1c7"
gray = "#928374"
level1 = "#ebdbb2"
level2 = "#d5c4a1"
level3 = "#bdae93"
level4 = "#a89984"

[theme.dark.green]
bright = "#b8bb26"
normal = "#98971a"

[theme.dark.orange]
bright = "#fe8019"
normal = "#d65d0e"

[theme.dark.purple]
bright = "#d3869b"
normal = "#b16286"

[theme.dark.red]
bright = "#fb4934"
normal = "#cc241d"

[theme.dark.yellow]
bright = "#fabd2f"
normal = "#d79921"
[theme.light.accent]
border_dark = "#cc241d"
border_light = "#fb4934"
bright = "#fb4934"
primary = "#cc241d"

[theme.light.aqua]
bright = "#8ec07c"
normal = "#689d6a"

[theme.light.background]
default = "#ebdbb2"
hard = "#fbf1c7"
level1 = "#ebdbb2"
level2 = "#d5c4a1"
level3 = "#bdae93"
level4 = "#a89984"
soft = "#fbf1c7"

[theme.light.foreground]
bright = "#282828"
gray = "#928374"
level1 = "#3c3836"
level2 = "#504945"
level3 = "#665c54"
level4 = "#7c6f64"

[theme.light.green]
bright = "#b8bb26"
normal = "#98971a"

[theme.light.orange]
bright = "#fe8019"
normal = "#d65d0e"

[theme.light.purple]
bright = "#d3869b"
normal = "#b16286"

[theme.light.red]
bright = "#fb4934"
normal = "#cc241d"

[theme.light.yellow]
bright = "#fabd2f"
normal = "#d79921"


[visualizer]
higher_cutoff_freq = 10000

lower_cutoff_freq = 50
monstercat = 0.0
noise_reduction = 0.77
waves = false


[visualizer.bars]
bar_spacing = 2.0
gradient_mode = "wave"
border_width = 1.0
led_bars = true
led_segment_height = 2.0
peak_gradient_mode = "cycle"
peak_mode = "fall"
peak_hold_time = 500
peak_fade_time = 750
bar_depth_3d = 0.0
peak_height_ratio = 66

[visualizer.bars.dark]
border_color = "#1d2021"
border_opacity = 1.0
led_border_opacity = 1.0
bar_gradient_colors = [
    "#cc241d",
    "#cc241d",
    "#fb4934",
    "#d65d0e",
    "#fe8019",
    "#fe8019",
]
peak_gradient_colors = [
    "#d79921",
    "#d79921",
    "#fabd2f",
    "#fabd2f",
    "#fabd2f",
    "#fabd2f",
]

[visualizer.bars.light]
border_color = "#fbf1c7"
border_opacity = 0.0
led_border_opacity = 0.0
bar_gradient_colors = [
    "#cc241d",
    "#cc241d",
    "#fb4934",
    "#d65d0e",
    "#fe8019",
    "#fe8019",
]
peak_gradient_colors = [
    "#d79921",
    "#d79921",
    "#fabd2f",
    "#fabd2f",
    "#fabd2f",
    "#fabd2f",
]

[visualizer.lines]
line_thickness = 0.025
point_count = 32

