name = "Catppuccin Macchiato"

[dark.background]
default = "#24273a"
hard = "#1b1d2c"
level1 = "#333756"
level2 = "#3a3f62"
level3 = "#3f456d"
level4 = "#454b77"
soft = "#2a2e46"

[dark.foreground]
bright = "#cad3f5"
gray = "#454b77"
level1 = "#cad3f5"
level2 = "#cad3f5"
level3 = "#cad3f5"
level4 = "#cad3f5"

[dark.accent]
border_dark = "#668dde"
border_light = "#6f8bc5"
bright = "#668dde"
primary = "#8aadf4"
selected = "#668dde"

[dark.danger]
bright = "#d36175"
base = "#ed8796"

[dark.success]
bright = "#87ba76"
base = "#a6da95"

[dark.warning]
bright = "#cdb480"
base = "#eed49f"

[dark.star]
bright = "#cdb480"
base = "#eed49f"

[dark.visualizer]
bar_gradient_colors = ["#8aadf4", "#8aadf4", "#6f8bc5", "#6f8bc5", "#668dde", "#668dde"]
border_color = "#1b1d2c"
border_opacity = 1.0
led_border_opacity = 1.0
peak_gradient_colors = ["#eed49f", "#eed49f", "#bfaa82", "#bfaa82", "#cdb480", "#cdb480"]

[light.background]
default = "#eff1f5"
hard = "#dcdee1"
level1 = "#d3dae8"
level2 = "#c8d0e2"
level3 = "#bec8dd"
level4 = "#b5c0d8"
soft = "#e3e7ef"

[light.foreground]
bright = "#4c4f69"
gray = "#b5c0d8"
level1 = "#4c4f69"
level2 = "#303357"
level3 = "#303357"
level4 = "#303357"

[light.accent]
border_dark = "#0178ff"
border_light = "#a0b0f5"
bright = "#0178ff"
primary = "#1e66f5"
selected = "#0178ff"

[light.danger]
bright = "#ff003b"
base = "#d20f39"

[light.success]
bright = "#008300"
base = "#40a02b"

[light.warning]
bright = "#be6f00"
base = "#df8e1d"

[light.star]
bright = "#be6f00"
base = "#df8e1d"

[light.visualizer]
bar_gradient_colors = ["#1e66f5", "#1e66f5", "#a0b0f5", "#a0b0f5", "#0178ff", "#0178ff"]
border_color = "#dcdee1"
border_opacity = 0.0
led_border_opacity = 0.0
peak_gradient_colors = ["#df8e1d", "#df8e1d", "#e6bea4", "#e6bea4", "#be6f00", "#be6f00"]
