name = "Catppuccin"

[dark]
border = "#101018"

[dark.background]
default = "#1e1e2e"
hard = "#171723"
level1 = "#2e2e49"
level2 = "#353554"
level3 = "#3b3a5f"
level4 = "#414069"
soft = "#252539"

[dark.foreground]
bright = "#cdd6f4"
gray = "#414069"
level1 = "#cdd6f4"
level2 = "#cdd6f4"
level3 = "#cdd6f4"
level4 = "#cdd6f4"

[dark.accent]
border_dark = "#6394e4"
border_light = "#6e90c9"
bright = "#6394e4"
primary = "#89b4fa"
selected = "#6394e4"

[dark.danger]
bright = "#d16c89"
base = "#f38ba8"

[dark.success]
bright = "#87c282"
base = "#a6e3a1"

[dark.warning]
bright = "#d8c190"
base = "#f9e2af"

[dark.star]
bright = "#d8c190"
base = "#f9e2af"

[dark.visualizer]
bar_gradient_colors = ["#89b4fa", "#89b4fa", "#6e90c9", "#6e90c9", "#6394e4", "#6394e4"]
border_color = "#171723"
border_opacity = 1.0
led_border_opacity = 1.0
peak_gradient_colors = ["#f9e2af", "#f9e2af", "#c7b58d", "#c7b58d", "#d8c190", "#d8c190"]

[light]
border = "#bbbcbf"

[light.background]
default = "#eff1f5"
hard = "#dcdee1"
level1 = "#d3dae8"
level2 = "#c8d0e2"
level3 = "#bec8dd"
level4 = "#b5c0d8"
soft = "#e3e7ef"

[light.foreground]
bright = "#4c4f69"
gray = "#b5c0d8"
level1 = "#4c4f69"
level2 = "#303357"
level3 = "#303357"
level4 = "#303357"

[light.accent]
border_dark = "#0178ff"
border_light = "#a0b0f5"
bright = "#0178ff"
primary = "#1e66f5"
selected = "#0178ff"

[light.danger]
bright = "#ff003b"
base = "#d20f39"

[light.success]
bright = "#008300"
base = "#40a02b"

[light.warning]
bright = "#be6f00"
base = "#df8e1d"

[light.star]
bright = "#be6f00"
base = "#df8e1d"

[light.visualizer]
bar_gradient_colors = ["#1e66f5", "#1e66f5", "#a0b0f5", "#a0b0f5", "#0178ff", "#0178ff"]
border_color = "#dcdee1"
border_opacity = 0.0
led_border_opacity = 0.0
peak_gradient_colors = ["#df8e1d", "#df8e1d", "#e6bea4", "#e6bea4", "#be6f00", "#be6f00"]
