name = "Catppuccin Frappé"

[dark.background]
default = "#303446"
hard = "#242735"
level1 = "#404661"
level2 = "#474d6c"
level3 = "#4d5476"
level4 = "#535b81"
soft = "#373b51"

[dark.foreground]
bright = "#c6d0f5"
gray = "#535b81"
level1 = "#c6d0f5"
level2 = "#c6d0f5"
level3 = "#e4f0ff"
level4 = "#e4f0ff"

[dark.accent]
border_dark = "#688ad8"
border_light = "#728ac2"
bright = "#688ad8"
primary = "#8caaee"
selected = "#688ad8"

[dark.danger]
bright = "#cd5c61"
base = "#e78284"

[dark.success]
bright = "#87b16a"
base = "#a6d189"

[dark.warning]
bright = "#c4a871"
base = "#e5c890"

[dark.star]
bright = "#c4a871"
base = "#e5c890"

[dark.visualizer]
bar_gradient_colors = ["#8caaee", "#8caaee", "#728ac2", "#728ac2", "#688ad8", "#688ad8"]
border_color = "#242735"
border_opacity = 1.0
led_border_opacity = 1.0
peak_gradient_colors = ["#e5c890", "#e5c890", "#b8a279", "#b8a279", "#c4a871", "#c4a871"]

[light.background]
default = "#eff1f5"
hard = "#dcdee1"
level1 = "#d3dae8"
level2 = "#c8d0e2"
level3 = "#bec8dd"
level4 = "#b5c0d8"
soft = "#e3e7ef"

[light.foreground]
bright = "#4c4f69"
gray = "#b5c0d8"
level1 = "#4c4f69"
level2 = "#303357"
level3 = "#303357"
level4 = "#303357"

[light.accent]
border_dark = "#0178ff"
border_light = "#a0b0f5"
bright = "#0178ff"
primary = "#1e66f5"
selected = "#0178ff"

[light.danger]
bright = "#ff003b"
base = "#d20f39"

[light.success]
bright = "#008300"
base = "#40a02b"

[light.warning]
bright = "#be6f00"
base = "#df8e1d"

[light.star]
bright = "#be6f00"
base = "#df8e1d"

[light.visualizer]
bar_gradient_colors = ["#1e66f5", "#1e66f5", "#a0b0f5", "#a0b0f5", "#0178ff", "#0178ff"]
border_color = "#dcdee1"
border_opacity = 0.0
led_border_opacity = 0.0
peak_gradient_colors = ["#df8e1d", "#df8e1d", "#e6bea4", "#e6bea4", "#be6f00", "#be6f00"]
