name = "Dracula"

[dark.background]
default = "#282a36"
hard = "#1e2029"
level1 = "#383b4e"
level2 = "#3f4359"
level3 = "#454962"
level4 = "#4c506b"
soft = "#2f3140"

[dark.foreground]
bright = "#f8f8f2"
gray = "#4c506b"
level1 = "#f8f8f2"
level2 = "#f8f8f2"
level3 = "#f8f8f2"
level4 = "#f8f8f2"

[dark.accent]
border_dark = "#9e74d7"
border_light = "#9877c9"
bright = "#9e74d7"
primary = "#bd93f9"
selected = "#9e74d7"

[dark.danger]
bright = "#da2f37"
base = "#ff5555"

[dark.success]
bright = "#13d85a"
base = "#50fa7b"

[dark.warning]
bright = "#d0d96b"
base = "#f1fa8c"

[dark.star]
bright = "#d0d96b"
base = "#f1fa8c"

[dark.visualizer]
bar_gradient_colors = ["#bd93f9", "#bd93f9", "#9877c9", "#9877c9", "#9e74d7", "#9e74d7"]
border_color = "#1e2029"
border_opacity = 1.0
led_border_opacity = 1.0
peak_gradient_colors = ["#f1fa8c", "#f1fa8c", "#c1c973", "#c1c973", "#d0d96b", "#d0d96b"]

[light.background]
default = "#282a36"
hard = "#1e2029"
level1 = "#383b4e"
level2 = "#3f4359"
level3 = "#454962"
level4 = "#4c506b"
soft = "#2f3140"

[light.foreground]
bright = "#f8f8f2"
gray = "#4c506b"
level1 = "#f8f8f2"
level2 = "#f8f8f2"
level3 = "#f8f8f2"
level4 = "#f8f8f2"

[light.accent]
border_dark = "#9e74d7"
border_light = "#9877c9"
bright = "#9e74d7"
primary = "#bd93f9"
selected = "#9e74d7"

[light.danger]
bright = "#da2f37"
base = "#ff5555"

[light.success]
bright = "#13d85a"
base = "#50fa7b"

[light.warning]
bright = "#d0d96b"
base = "#f1fa8c"

[light.star]
bright = "#d0d96b"
base = "#f1fa8c"

[light.visualizer]
bar_gradient_colors = ["#bd93f9", "#bd93f9", "#9877c9", "#9877c9", "#9e74d7", "#9e74d7"]
border_color = "#1e2029"
border_opacity = 0.0
led_border_opacity = 0.0
peak_gradient_colors = ["#f1fa8c", "#f1fa8c", "#c1c973", "#c1c973", "#d0d96b", "#d0d96b"]
