name = "Ember"

[dark.background]
default = "#181412"
hard = "#0c0a09"
level1 = "#292524"
level2 = "#44403c"
level3 = "#57534e"
level4 = "#78716c"
soft = "#1c1917"

[dark.foreground]
bright = "#fafaf9"
gray = "#a8a29e"
level1 = "#e7e5e4"
level2 = "#d6d3d1"
level3 = "#a8a29e"
level4 = "#78716c"

[dark.accent]
border_dark = "#1c1917"
border_light = "#292524"
bright = "#f59e0b"
primary = "#b45309"

[dark.danger]
bright = "#f87171"
base = "#dc2626"

[dark.success]
bright = "#4ade80"
base = "#15803d"

[dark.warning]
bright = "#fde047"
base = "#ca8a04"

[dark.star]
bright = "#fde047"
base = "#ca8a04"

[dark.visualizer]
bar_gradient_colors = ["#92400e", "#b45309", "#d97706", "#f59e0b", "#fde047", "#4ade80"]
border_color = "#0c0a09"
border_opacity = 1.0
led_border_opacity = 1
peak_gradient_colors = ["#7c2d12", "#b91c1c", "#ea580c", "#f59e0b", "#fde047", "#22c55e"]

[light.background]
default = "#faf7f2"
hard = "#f5f5f4"
level1 = "#d6d3d1"
level2 = "#a8a29e"
level3 = "#78716c"
level4 = "#57534e"
soft = "#e7e5e4"

[light.foreground]
bright = "#1c1917"
gray = "#57534e"
level1 = "#292524"
level2 = "#44403c"
level3 = "#57534e"
level4 = "#78716c"

[light.accent]
border_dark = "#d6d3d1"
border_light = "#a8a29e"
bright = "#b45309"
primary = "#92400e"

[light.danger]
bright = "#dc2626"
base = "#b91c1c"

[light.success]
bright = "#22c55e"
base = "#166534"

[light.warning]
bright = "#ca8a04"
base = "#a16207"

[light.star]
bright = "#ca8a04"
base = "#a16207"

[light.visualizer]
bar_gradient_colors = ["#a16207", "#b45309", "#c2410c", "#ea580c", "#ca8a04", "#22c55e"]
border_color = "#f5f5f4"
border_opacity = 0.0
led_border_opacity = 0.0
peak_gradient_colors = ["#991b1b", "#c2410c", "#ea580c", "#ca8a04", "#16a34a", "#0d9488"]
