name = "Everforest"

[dark.background]
default = "#2D353B"
hard = "#232A2E"
level1 = "#343F44"
level2 = "#3D484D"
level3 = "#475258"
level4 = "#4F585E"
soft = "#2D353B"

[dark.foreground]
bright = "#D3C6AA"
gray = "#7A8478"
level1 = "#D3C6AA"
level2 = "#9DA9A0"
level3 = "#859289"
level4 = "#7A8478"

[dark.accent]
border_dark = "#8DA101"
border_light = "#A7C080"
bright = "#A7C080"
now_playing = "#A7C080"
primary = "#8DA101"
selected = "#8CA16E"

[dark.danger]
bright = "#E67E80"
base = "#E67E80"

[dark.success]
bright = "#A7C080"
base = "#A7C080"

[dark.warning]
bright = "#DBBC7F"
base = "#DBBC7F"

[dark.star]
bright = "#DBBC7F"
base = "#DBBC7F"

[dark.visualizer]
bar_gradient_colors = ["#A7C080", "#A7C080", "#A7C080", "#83C092", "#7FBBB3", "#DBBC7F"]
border_color = "#232A2E"
border_opacity = 1.0
led_border_opacity = 1.0
peak_gradient_colors = ["#E67E80", "#E69875", "#DBBC7F", "#D699B6", "#E67E80", "#E69875"]

[light.background]
default = "#FDF6E3"
hard = "#EFEBD4"
level1 = "#E6E2CC"
level2 = "#E0DCC7"
level3 = "#BDC3AF"
level4 = "#A6B0A0"
soft = "#FDF6E3"

[light.foreground]
bright = "#5C6A72"
gray = "#A6B0A0"
level1 = "#5C6A72"
level2 = "#708089"
level3 = "#829181"
level4 = "#939F91"

[light.accent]
border_dark = "#5C6A72"
border_light = "#E6E2CC"
bright = "#93B259"
now_playing = "#93B259"
primary = "#8DA101"
selected = "#A6B0A0"

[light.danger]
bright = "#F85552"
base = "#F85552"

[light.success]
bright = "#8DA101"
base = "#8DA101"

[light.warning]
bright = "#DFA000"
base = "#DFA000"

[light.star]
bright = "#DFA000"
base = "#DFA000"

[light.visualizer]
bar_gradient_colors = ["#93B259", "#8DA101", "#8DA101", "#35A77C", "#35A77C", "#3A94C5"]
border_color = "#EFEBD4"
border_opacity = 0.0
led_border_opacity = 0.0
peak_gradient_colors = ["#F57D26", "#DFA000", "#F57D26", "#DFA000", "#F57D26", "#DFA000"]
