name = "Gruvbox"

[dark.background]
default = "#282828"
hard = "#1e1e1e"
level1 = "#3a3a3a"
level2 = "#414141"
level3 = "#484848"
level4 = "#4f4f4f"
soft = "#2f2f2f"

[dark.foreground]
bright = "#fbf1c7"
gray = "#4f4f4f"
level1 = "#fbf1c7"
level2 = "#fbf1c7"
level3 = "#fbf1c7"
level4 = "#fbf1c7"

[dark.accent]
border_dark = "#49a8ac"
border_light = "#3b6c6e"
bright = "#49a8ac"
primary = "#458588"
selected = "#49a8ac"

[dark.danger]
bright = "#ff0000"
base = "#cc241d"

[dark.success]
bright = "#7c7900"
base = "#98971a"

[dark.warning]
bright = "#b67a00"
base = "#d79921"

[dark.star]
bright = "#b67a00"
base = "#d79921"

[dark.visualizer]
bar_gradient_colors = ["#83a598", "#8ec07c", "#b8bb26", "#fabd2f", "#fe8019", "#fb4934"]
border_color = "#1e1e1e"
border_opacity = 1.0
led_border_opacity = 1.0
peak_gradient_colors = ["#83a598", "#83a598", "#b8bb26", "#b8bb26", "#fb4934", "#fb4934"]

[light.background]
default = "#fbf1c7"
hard = "#e7deb7"
level1 = "#e4dab1"
level2 = "#dad0a7"
level3 = "#d2c89f"
level4 = "#cac097"
soft = "#f1e7bd"

[light.foreground]
bright = "#282828"
gray = "#cac097"
level1 = "#282828"
level2 = "#282828"
level3 = "#282828"
level4 = "#282828"

[light.accent]
border_dark = "#49a8ac"
border_light = "#aebaa5"
bright = "#49a8ac"
primary = "#458588"
selected = "#49a8ac"

[light.danger]
bright = "#ff0000"
base = "#cc241d"

[light.success]
bright = "#7c7900"
base = "#98971a"

[light.warning]
bright = "#b67a00"
base = "#d79921"

[light.star]
bright = "#b67a00"
base = "#d79921"

[light.visualizer]
bar_gradient_colors = ["#83a598", "#8ec07c", "#b8bb26", "#fabd2f", "#fe8019", "#fb4934"]
border_color = "#e7deb7"
border_opacity = 0.0
led_border_opacity = 0.0
peak_gradient_colors = ["#83a598", "#83a598", "#b8bb26", "#b8bb26", "#fb4934", "#fb4934"]
