name = "Gruvbox Red"

[dark.background]
default = "#282828"
hard = "#1d2021"
level1 = "#3c3836"
level2 = "#504945"
level3 = "#665c54"
level4 = "#7c6f64"
soft = "#32302f"

[dark.foreground]
bright = "#fbf1c7"
gray = "#928374"
level1 = "#ebdbb2"
level2 = "#d5c4a1"
level3 = "#bdae93"
level4 = "#a89984"

[dark.accent]
border_dark = "#cc241d"
border_light = "#fb4934"
bright = "#fb4934"
primary = "#cc241d"

[dark.danger]
bright = "#fb4934"
base = "#cc241d"

[dark.success]
bright = "#b8bb26"
base = "#98971a"

[dark.warning]
bright = "#fabd2f"
base = "#d79921"

[dark.star]
bright = "#fabd2f"
base = "#d79921"

[dark.visualizer]
bar_gradient_colors = ["#cc241d", "#cc241d", "#fb4934", "#d65d0e", "#fe8019", "#fe8019"]
border_color = "#1d2021"
border_opacity = 1.0
led_border_opacity = 1.0
peak_gradient_colors = ["#d79921", "#d79921", "#fabd2f", "#fabd2f", "#fabd2f", "#fabd2f"]

[light.background]
default = "#ebdbb2"
hard = "#fbf1c7"
level1 = "#ebdbb2"
level2 = "#d5c4a1"
level3 = "#bdae93"
level4 = "#a89984"
soft = "#fbf1c7"

[light.foreground]
bright = "#282828"
gray = "#928374"
level1 = "#3c3836"
level2 = "#504945"
level3 = "#665c54"
level4 = "#7c6f64"

[light.accent]
border_dark = "#cc241d"
border_light = "#fb4934"
bright = "#fb4934"
primary = "#cc241d"

[light.danger]
bright = "#fb4934"
base = "#cc241d"

[light.success]
bright = "#b8bb26"
base = "#98971a"

[light.warning]
bright = "#fabd2f"
base = "#d79921"

[light.star]
bright = "#fabd2f"
base = "#d79921"

[light.visualizer]
bar_gradient_colors = ["#cc241d", "#cc241d", "#fb4934", "#d65d0e", "#fe8019", "#fe8019"]
border_color = "#fbf1c7"
border_opacity = 0.0
led_border_opacity = 0.0
peak_gradient_colors = ["#d79921", "#d79921", "#fabd2f", "#fabd2f", "#fabd2f", "#fabd2f"]
