name = "Kanagawa Dragon"

[dark.background]
default = "#181616"
hard = "#121111"
level1 = "#2a2626"
level2 = "#322d2d"
level3 = "#383333"
level4 = "#3f3a3a"
soft = "#1f1d1d"

[dark.foreground]
bright = "#c5c9c5"
gray = "#3f3a3a"
level1 = "#c5c9c5"
level2 = "#c5c9c5"
level3 = "#c5c9c5"
level4 = "#c5c9c5"

[dark.accent]
border_dark = "#304c75"
border_light = "#1e293b"
bright = "#304c75"
primary = "#223249"
selected = "#304c75"

[dark.danger]
bright = "#ac504b"
base = "#c4746e"

[dark.success]
bright = "#697e53"
base = "#8a9a7b"

[dark.warning]
bright = "#dd7e00"
base = "#ff9e3b"

[dark.star]
bright = "#dd7e00"
base = "#ff9e3b"

[dark.visualizer]
bar_gradient_colors = ["#223249", "#223249", "#1e293b", "#1e293b", "#304c75", "#304c75"]
border_color = "#121111"
border_opacity = 1.0
led_border_opacity = 1.0
peak_gradient_colors = ["#ff9e3b", "#ff9e3b", "#cc7e30", "#cc7e30", "#dd7e00", "#dd7e00"]

[light.background]
default = "#f2ecbc"
hard = "#dfd9ad"
level1 = "#dbd5a6"
level2 = "#d1cb9c"
level3 = "#c9c395"
level4 = "#c1bb8d"
soft = "#e8e2b2"

[light.foreground]
bright = "#545464"
gray = "#c1bb8d"
level1 = "#383852"
level2 = "#383852"
level3 = "#383852"
level4 = "#383852"

[light.accent]
border_dark = "#5d85ce"
border_light = "#aaada9"
bright = "#5d85ce"
primary = "#4d699b"
selected = "#5d85ce"

[light.danger]
bright = "#ff3d61"
base = "#c84053"

[light.success]
bright = "#87ab57"
base = "#6f894e"

[light.warning]
bright = "#c76b00"
base = "#e98a00"

[light.star]
bright = "#c76b00"
base = "#e98a00"

[light.visualizer]
bar_gradient_colors = ["#4d699b", "#4d699b", "#aaada9", "#aaada9", "#5d85ce", "#5d85ce"]
border_color = "#dfd9ad"
border_opacity = 0.0
led_border_opacity = 0.0
peak_gradient_colors = ["#e98a00", "#e98a00", "#edb97c", "#edb97c", "#c76b00", "#c76b00"]
