name = "Kanagawa"

[dark]
border = "#101015"

[dark.background]
default = "#1f1f28"
hard = "#17171e"
level1 = "#2f2f3e"
level2 = "#373749"
level3 = "#3d3d51"
level4 = "#43435a"
soft = "#262631"

[dark.foreground]
bright = "#dcd7ba"
gray = "#43435a"
level1 = "#dcd7ba"
level2 = "#dcd7ba"
level3 = "#dcd7ba"
level4 = "#dcd7ba"

[dark.accent]
border_light = "#6690a2"
bright = "#4e97b3"
primary = "#7fb4ca"
selected = "#4e97b3"

[dark.danger]
bright = "#ff3e4a"
base = "#c34043"

[dark.success]
bright = "#537843"
base = "#76946a"

[dark.warning]
bright = "#dd7e00"
base = "#ff9e3b"

[dark.star]
bright = "#dd7e00"
base = "#ff9e3b"

[dark.visualizer]
bar_gradient_colors = ["#7fb4ca", "#7fb4ca", "#6690a2", "#6690a2", "#4e97b3", "#4e97b3"]
border_color = "#17171e"
border_opacity = 1.0
led_border_opacity = 1.0
peak_gradient_colors = ["#ff9e3b", "#ff9e3b", "#cc7f34", "#cc7f34", "#dd7e00", "#dd7e00"]

[light]
border = "#bdb893"

[light.background]
default = "#f2ecbc"
hard = "#dfd9ad"
level1 = "#dbd5a6"
level2 = "#d1cb9c"
level3 = "#c9c395"
level4 = "#c1bb8d"
soft = "#e8e2b2"

[light.foreground]
bright = "#545464"
gray = "#c1bb8d"
level1 = "#383852"
level2 = "#383852"
level3 = "#383852"
level4 = "#383852"

[light.accent]
border_light = "#aaada9"
bright = "#5d85ce"
primary = "#4d699b"
selected = "#5d85ce"

[light.danger]
bright = "#ff3d61"
base = "#c84053"

[light.success]
bright = "#87ab57"
base = "#6f894e"

[light.warning]
bright = "#c76b00"
base = "#e98a00"

[light.star]
bright = "#c76b00"
base = "#e98a00"

[light.visualizer]
bar_gradient_colors = ["#4d699b", "#4d699b", "#aaada9", "#aaada9", "#5d85ce", "#5d85ce"]
border_color = "#dfd9ad"
border_opacity = 0.0
led_border_opacity = 0.0
peak_gradient_colors = ["#e98a00", "#e98a00", "#edb97c", "#edb97c", "#c76b00", "#c76b00"]
