name = "Nord"

[dark.background]
default = "#2e3440"
hard = "#232730"
level1 = "#3d4658"
level2 = "#444e63"
level3 = "#4a556c"
level4 = "#4f5c75"
soft = "#343c4a"

[dark.foreground]
bright = "#eceff4"
gray = "#4f5c75"
level1 = "#eceff4"
level2 = "#eceff4"
level3 = "#eceff4"
level4 = "#eceff4"

[dark.accent]
border_dark = "#5ea09f"
border_light = "#749899"
bright = "#5ea09f"
primary = "#8fbcbb"
selected = "#5ea09f"

[dark.danger]
bright = "#a63b4a"
base = "#bf616a"

[dark.success]
bright = "#80a162"
base = "#a3be8c"

[dark.warning]
bright = "#caab6c"
base = "#ebcb8b"

[dark.star]
bright = "#caab6c"
base = "#ebcb8b"

[dark.visualizer]
bar_gradient_colors = ["#8fbcbb", "#8fbcbb", "#749899", "#749899", "#5ea09f", "#5ea09f"]
border_color = "#232730"
border_opacity = 1.0
led_border_opacity = 1.0
peak_gradient_colors = ["#ebcb8b", "#ebcb8b", "#bda474", "#bda474", "#caab6c", "#caab6c"]

[light.background]
default = "#2e3440"
hard = "#232730"
level1 = "#3d4658"
level2 = "#444e63"
level3 = "#4a556c"
level4 = "#4f5c75"
soft = "#343c4a"

[light.foreground]
bright = "#eceff4"
gray = "#4f5c75"
level1 = "#eceff4"
level2 = "#eceff4"
level3 = "#eceff4"
level4 = "#eceff4"

[light.accent]
border_dark = "#5ea09f"
border_light = "#749899"
bright = "#5ea09f"
primary = "#8fbcbb"
selected = "#5ea09f"

[light.danger]
bright = "#a63b4a"
base = "#bf616a"

[light.success]
bright = "#80a162"
base = "#a3be8c"

[light.warning]
bright = "#caab6c"
base = "#ebcb8b"

[light.star]
bright = "#caab6c"
base = "#ebcb8b"

[light.visualizer]
bar_gradient_colors = ["#8fbcbb", "#8fbcbb", "#749899", "#749899", "#5ea09f", "#5ea09f"]
border_color = "#232730"
border_opacity = 0.0
led_border_opacity = 0.0
peak_gradient_colors = ["#ebcb8b", "#ebcb8b", "#bda474", "#bda474", "#caab6c", "#caab6c"]
